version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: streaming-musical-dev
    ports:
      - "3000:3000"  # Puerto de desarrollo de Vite
      - "24678:24678"
    env_file:
      - .env  # Cargar variables de entorno
    environment:
      - NODE_ENV=development
      - VITE_WS_HOST=localhost
      - VITE_WS_PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"

networks:
  app-network:
    driver: bridge